# ------------------------------------------------------------
# Incentive IQ Portal – multi-stage Docker build
# ------------------------------------------------------------

# 1. Builder stage: install deps & run Next.js build
FROM node:20-alpine AS builder
WORKDIR /app

# Install only production-safe deps using package lock
COPY package*.json ./
RUN npm ci

# Copy source and build with the default Next CLI
COPY . .
RUN npm run build

# 2. Runtime stage: serve the standalone output
FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production

# Copy the standalone server bundle and assets generated by `next build`
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

# App listens on 3006 (nginx upstream expects this)
ENV PORT=3006
EXPOSE 3006

# Launch the standalone Next.js server
CMD ["node", "server.js"]

